/**
 * Stage `upload` — the finished video to Mux, with captions requested.
 *
 *   pnpm video upload /saql/functions [--file=final.mp4] [--test] [--policy=signed|public] [--no-write]
 *
 * Default file: .data/video/<route>/final.mp4 (Premiere's export). The
 * playback policy follows the lesson — signed for `access: pro` (it plays only
 * with the token /api/lesson mints after hasPro), public otherwise. The new
 * asset asks Mux for auto-generated English captions, which the `captions`
 * stage later syncs into content-transcripts/en/ for translation.
 *
 * Writes `mux: <playback id>` — ONE id, not a per-language map — into the
 * English lesson's frontmatter. `--no-write` only prints the id, for a video
 * that goes inside a `::pro` block as `:::lesson-video{mux="…"}` (use
 * --policy=signed for those).
 */
import { existsSync } from 'node:fs'
import path from 'node:path'
import { setFrontmatter } from '../../lib/lessons.mjs'
import { fail } from '../lib/context.mjs'
import { muxMode, uploadVideo } from '../lib/mux.mjs'

export async function run(ctx) {
  const file = path.resolve(String(ctx.flags.file || ctx.at('final.mp4')).replace(/^~/, process.env.HOME ?? '~'))
  if (!existsSync(file)) fail(`No video at ${ctx.rel(file)}. Export from Premiere to that path (see PREMIERE.md), or pass --file=…`)
  const access = ctx.lesson.data.access === 'pro' ? 'pro' : 'free'
  const policy = ctx.flags.policy || (access === 'pro' ? 'signed' : 'public')
  if (!['signed', 'public'].includes(policy)) fail('--policy must be signed or public.')
  const write = !ctx.flags['no-write']

  console.log(`upload: ${ctx.rel(file)} → ${ctx.route} (${access} lesson, ${policy} playback, via ${muxMode()})`)
  const asset = await uploadVideo(file, {
    policy,
    passthrough: `lesson:${ctx.route}`,
    quality: ctx.config.upload?.videoQuality ?? 'basic',
    test: Boolean(ctx.flags.test),
    captions: ctx.config.upload?.captions
  })
  const playbackId = (asset.playback_ids ?? []).find(p => p.policy === policy)?.id ?? asset.playback_ids?.[0]?.id
  if (!playbackId) fail(`Uploaded asset ${asset.id} has no playback id.`)

  ctx.writeJson('upload.json', { assetId: asset.id, playbackId, policy, test: Boolean(ctx.flags.test), at: new Date().toISOString() })
  console.log(`✓ asset ${asset.id}  playback ${playbackId} (${policy})`)
  if (write) {
    setFrontmatter(ctx.file, 'mux', playbackId)
    console.log(`✓ ${ctx.rel(ctx.file)} → mux: ${playbackId}`)
  } else {
    console.log(`  Paste into a ::pro block:\n  :::lesson-video{mux="${playbackId}"}\n  :::`)
  }
  if (policy === 'signed') console.log('  Signed video: the Worker needs MUX_SIGNING_KEY_ID / MUX_SIGNING_KEY_SECRET (mux signing-keys create).')
  console.log(`  Captions are generated by Mux in a few minutes; then: pnpm video captions ${ctx.route}`)
}
