/**
 * Loads ../content (English lessons, showcase, resources) into Payload.
 *
 *   pnpm content:import    upsert everything, keyed on the file path
 *
 * Safe to re-run: every record is matched on `file`, so a second run updates
 * rather than duplicates. Only content/en is read — the other locales are
 * generated by the site's translation pipeline and never authored here.
 */
import path from 'node:path'
import config from '@payload-config'
import { getPayload } from 'payload'
import YAML from 'yaml'
import { readFileSync, existsSync } from 'node:fs'
import {
  CONTENT, lessonFromMarkdown, listDirs, listMarkdown, readMarkdown, resourceFromMarkdown,
  showcaseFromMarkdown, splitPrefix
} from './markdown'

const payload = await getPayload({ config })
const counts = { sections: 0, lessons: 0, showcase: 0, resources: 0 }

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function upsert(collection: 'sections' | 'lessons' | 'showcase' | 'resources', file: string, data: any) {
  const found = await payload.find({ collection, where: { file: { equals: file } }, limit: 1, depth: 0, overrideAccess: true })
  const existing = found.docs[0]
  const doc = existing
    ? await payload.update({ collection, id: existing.id, data, overrideAccess: true, depth: 0 })
    : await payload.create({ collection, data: { ...data, file }, overrideAccess: true, depth: 0 })
  counts[collection]++
  return doc
}

// Sections and their lessons
const en = path.join(CONTENT, 'en')
for (const dir of listDirs(en)) {
  const { order, slug } = splitPrefix(dir)
  const navFile = path.join(en, dir, '.navigation.yml')
  const nav = existsSync(navFile) ? (YAML.parse(readFileSync(navFile, 'utf8')) ?? {}) : {}
  const section = await upsert('sections', `en/${dir}`, { title: nav.title ?? slug, slug, order, icon: nav.icon })

  for (const name of listMarkdown(path.join(en, dir))) {
    const { order: lessonOrder, slug: lessonSlug } = splitPrefix(name)
    const { data, body } = readMarkdown(path.join(en, dir, name))
    const { accessSet: _accessSet, ...lesson } = lessonFromMarkdown(data, body)
    await upsert('lessons', `en/${dir}/${name}`, { ...lesson, section: section.id, order: lessonOrder, slug: lessonSlug })
  }
}

for (const name of listMarkdown(path.join(CONTENT, 'showcase'))) {
  const { data, body } = readMarkdown(path.join(CONTENT, 'showcase', name))
  await upsert('showcase', `showcase/${name}`, { ...showcaseFromMarkdown(data, body), slug: name.replace(/\.md$/, '') })
}

for (const name of listMarkdown(path.join(CONTENT, 'resources'))) {
  const { data } = readMarkdown(path.join(CONTENT, 'resources', name))
  const { featuredSet: _featuredSet, ...resource } = resourceFromMarkdown(data)
  await upsert('resources', `resources/${name}`, { ...resource, slug: name.replace(/\.md$/, '') })
}

payload.logger.info(`Imported ${JSON.stringify(counts)}`)
process.exit(0)
