#!/usr/bin/env node
/**
 * Offline checks for the transcript and inline-Pro machinery. No network, no
 * translation server: the translator is a fake.
 *
 *   node scripts/video/test-vtt.mjs        (also: pnpm video test)
 *
 * 1. A VTT parses and serialises back byte for byte.
 * 2. Through translate.mjs's protect/restore layer with an identity
 *    translator, a transcript comes back unchanged.
 * 3. With a translator that rewrites every word, every timing line, cue id,
 *    NOTE/STYLE block and separator is untouched and only cue text changed.
 * 4. `::pro` blocks split, get replaced by placeholders that contain none of
 *    their words, and a mis-nested `::component` inside one is an error.
 */
import assert from 'node:assert/strict'
import { parseVtt, serializeVtt, cuesOf, cuesToSrt } from '../lib/vtt.mjs'
import { splitProBlocks, placeholder, stripProBlocks, muxIdsIn } from '../lib/pro-blocks.mjs'
import { translateTranscript } from '../translate.mjs'

const SAMPLE = `WEBVTT - CRM Analytics Academy
Kind: captions
Language: en

NOTE
Generated by Mux, synced by scripts/video/captions.mjs

STYLE
::cue { color: white }

1
00:00:00.000 --> 00:00:03.250 align:start position:10%
Welcome to CRM Analytics Academy.

intro-2
00:00:03.250 --> 00:00:07.900
In this lesson we build a <b>recipe</b>
that joins Opportunity & Account.

00:00:07.900 --> 00:01:02.000
SAQL runs \`q = load "opps";\` first — 100% of the time.

01:00:00.000 --> 01:00:04.000
<v Swarnil>Thanks for watching.
`

let failures = 0
function check(name, fn) {
  return Promise.resolve()
    .then(fn)
    .then(() => console.log(`  ok  ${name}`))
    .catch((e) => {
      failures++
      console.error(`  FAIL ${name}\n       ${e.message.split('\n').join('\n       ')}`)
    })
}

/** html fragments → Map(fragment → fn(fragment)), the shape translateAll returns. */
const fakeTranslator = fn => async strings => new Map(strings.map(s => [s, fn(s)]))

console.log('vtt')
await check('round-trips byte for byte', () => {
  assert.equal(serializeVtt(parseVtt(SAMPLE)), SAMPLE)
  const crlf = SAMPLE.replace(/\n/g, '\r\n')
  assert.equal(serializeVtt(parseVtt(crlf)), crlf)
})
await check('finds every cue with its timing', () => {
  const cues = cuesOf(SAMPLE)
  assert.equal(cues.length, 4)
  assert.deepEqual(cues.map(c => [c.start, c.end]), [[0, 3.25], [3.25, 7.9], [7.9, 62], [3600, 3604]])
  assert.match(cuesToSrt(cues), /^1\n00:00:00,000 --> 00:00:03,250\n/)
})
await check('identity translation leaves the file unchanged', async () => {
  const { text, kept } = await translateTranscript(SAMPLE, fakeTranslator(s => s))
  assert.equal(kept, 0)
  assert.equal(text, SAMPLE)
})
await check('a real-looking translation changes only cue text', async () => {
  // Uppercase every word OUTSIDE tags — what a translator does to prose — and
  // leave the <v_n> atom tags alone, as LibreTranslate does in html mode.
  const shout = s => s.replace(/(^|>)([^<]+)/g, (_, a, b) => a + b.toUpperCase())
  const { text, kept } = await translateTranscript(SAMPLE, fakeTranslator(shout))
  assert.equal(kept, 0)
  const before = parseVtt(SAMPLE)
  const after = parseVtt(text)
  assert.deepEqual(after.separators, before.separators)
  assert.equal(after.blocks.length, before.blocks.length)
  before.blocks.forEach((b, i) => {
    const a = after.blocks[i]
    assert.equal(a.kind, b.kind)
    if (b.kind !== 'cue') return assert.equal(a.raw, b.raw)
    assert.equal(a.id, b.id)
    assert.equal(a.timing, b.timing)
    assert.equal(a.lines.length, b.lines.length)
  })
  // Glossary terms (CRM Analytics) are held untranslated by the protect layer.
  assert.match(text, /WELCOME TO CRM Analytics ACADEMY\./)
  // Code spans, tags and & are atoms: they survive verbatim.
  assert.match(text, /`q = load "opps";`/)
  assert.match(text, /<b>RECIPE<\/b>/)
  assert.match(text, /OPPORTUNITY & ACCOUNT/)
  assert.match(text, /<v Swarnil>THANKS FOR WATCHING\./)
})
await check('a failed batch keeps English and is counted', async () => {
  const { text, kept } = await translateTranscript(SAMPLE, async () => new Map())
  assert.equal(kept, 4)
  assert.equal(text, SAMPLE)
})

console.log('pro blocks')
const LESSON = `# Title

Free intro paragraph.

::pro
## The worked example

Secret paragraph one about binding syntax internals.

- secret list item

\`\`\`saql
q = load "x";
::
\`\`\`

:::lesson-video{mux="AbC123xyz"}
:::
::

Free outro.
`
await check('splits and replaces a block', () => {
  const { blocks, errors } = splitProBlocks(LESSON)
  assert.deepEqual(errors, [])
  assert.equal(blocks.length, 1)
  assert.match(blocks[0].markdown, /Secret paragraph one/)
  // The `::` inside a code fence did not close the block.
  assert.match(blocks[0].markdown, /:::lesson-video/)
  const pub = stripProBlocks(LESSON)
  assert.doesNotMatch(pub, /Secret|binding syntax|AbC123xyz/)
  assert.match(pub, /Free intro[\s\S]*Free outro/)
  const ph = placeholder({ locale: 'en', route: '/saql/functions', block: blocks[0] })
  assert.match(ph, /^::pro-locked\{id="en\/saql\/functions#1" teaser="The worked example" paragraphs="2" videos="1" code="1" tables="0" minutes="1"\}\n::$/)
  assert.doesNotMatch(ph, /Secret/)
  assert.deepEqual(muxIdsIn(blocks[0].markdown), ['AbC123xyz'])
})
await check('two-colon component inside ::pro is an error', () => {
  const { errors } = splitProBlocks('::pro\ntext\n::youtube-embed{id="x"}\n::\n::\n')
  assert.equal(errors.length, 1)
})
await check('unclosed ::pro fails closed', () => {
  const { blocks, errors } = splitProBlocks('free\n::pro\nsecret to the end\n')
  assert.equal(errors.length, 1)
  assert.equal(stripProBlocks('free\n::pro\nsecret to the end\n').includes('secret'), false)
  assert.equal(blocks.length, 1)
})

if (failures) {
  console.error(`\n${failures} check(s) failed`)
  process.exit(1)
}
console.log('\nall checks passed')
